version: "3.8"
services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "./docker-entrypoint.sh dotnet Dfe.Academies.External.Web.dll"
    ports:
      - 80:80/tcp
    env_file:
       - .env.development.local
