name: Deploy to environment

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: "Choose an environment to deploy to"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  NODE_VERSION: 18.x

jobs:
  set-env:
    name: Determine environment
    runs-on: ubuntu-22.04
    outputs:
      environment: ${{ steps.var.outputs.environment }}
      release: ${{ steps.var.outputs.release }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: var
        run: |
          INPUT=${{ github.event.inputs.environment }}
          ENVIRONMENT=${INPUT:-"development"}
          RELEASE=${ENVIRONMENT,,}-`date +%Y-%m-%d`.${{ github.run_number }}
          echo "environment=${ENVIRONMENT,,}" >> $GITHUB_OUTPUT
          echo "release=${RELEASE}" >> $GITHUB_OUTPUT

  deploy-image:
    name: Deploy
    needs: [ set-env ]
    uses: DFE-Digital/deploy-azure-container-apps-action/.github/workflows/build-push-deploy.yml@v2.0.0
    with:
      docker-image-name: 'a2bext-app'
      docker-build-file-name: './Dockerfile'
      environment: ${{ needs.set-env.outputs.environment }}
    secrets:
      azure-acr-credentials: ${{ secrets.ACR_CREDENTIALS }}
      azure-acr-name: ${{ secrets.ACR_NAME }}
      azure-aca-credentials: ${{ secrets.ACA_CREDENTIALS }}
      azure-aca-name: ${{ secrets.ACA_CONTAINERAPP_NAME }}
      azure-aca-resource-group: ${{ secrets.ACA_RESOURCE_GROUP }}

  create-tag:
    name: Tag and release
    needs: [ set-env, deploy-image ]
    runs-on: ubuntu-22.04
    if: needs.set-env.outputs.environment == 'production'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Create tag
        run: |
          git tag ${{ needs.set-env.outputs.release }}
          git push origin ${{ needs.set-env.outputs.release }}

      - name: Create release
        uses: "actions/github-script@v7"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            try {
              await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: "${{ needs.set-env.outputs.release }}",
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: "${{ needs.set-env.outputs.release }}",
              });
            } catch (error) {
              core.setFailed(error.message);
            }

  cypress-tests:
      needs: [ deploy-image, set-env ]
      if: needs.set-env.outputs.environment == 'test' || needs.set-env.outputs.environment == 'development'
      environment: ${{ needs.set-env.outputs.environment }}
      runs-on: ubuntu-22.04
      defaults:
        run:
          working-directory: Dfe.Academies.External.Web/CypressTests
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup node.js
          uses: actions/setup-node@v4
          with:
            node-version: ${{ env.NODE_VERSION }}

        - name: Npm install
          run: npm install

        - name: Run cypress
          env:
            URL: ${{ secrets.URL }}
            LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
            LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
          run: npm run cy:run

        - name: upload report
          uses: actions/upload-artifact@v4
          if: failure()
          with:
            name: screenshots
            path: Dfe.Academies.External.Web/CypressTests/cypress/screenshots
