name: Deploy to environment

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: "Choose an environment to deploy to"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  DOCKER_IMAGE: a2bext-app
  NODE_VERSION: 18.x

jobs:
  set-env:
    name: Determine environment
    runs-on: ubuntu-22.04
    outputs:
      environment: ${{ steps.var.outputs.environment }}
      branch: ${{ steps.var.outputs.branch }}
      release: ${{ steps.var.outputs.release }}
    steps:
      - id: var
        run: |
          GIT_REF=${{ github.ref }}
          GIT_BRANCH=${GIT_REF##*/}
          INPUT=${{ github.event.inputs.environment }}
          ENVIRONMENT=${INPUT:-"development"}
          RELEASE=${ENVIRONMENT,,}-`date +%Y-%m-%d`.${{ github.run_number }}
          echo "environment=${ENVIRONMENT,,}" >> $GITHUB_OUTPUT
          echo "branch=$GIT_BRANCH" >> $GITHUB_OUTPUT
          echo "release=${RELEASE}" >> $GITHUB_OUTPUT

  build-and-push-image:
    name: Build and push to ACR
    needs: set-env
    runs-on: ubuntu-22.04
    environment: ${{ needs.set-env.outputs.environment }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Azure Container Registry login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ACR_CLIENTID }}
          password: ${{ secrets.ACR_SECRET }}
          registry: ${{ secrets.ACR_URL }}

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          secrets: github_token=${{ secrets.GITHUB_TOKEN }}
          tags: |
            ${{ secrets.ACR_URL }}/${{ env.DOCKER_IMAGE }}:${{ needs.set-env.outputs.branch }}
            ${{ secrets.ACR_URL }}/${{ env.DOCKER_IMAGE }}:${{ needs.set-env.outputs.release }}
            ${{ secrets.ACR_URL }}/${{ env.DOCKER_IMAGE }}:latest
          push: true

  create-tag:
    name: Tag and release
    needs: set-env
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Create tag
        run: |
          git tag ${{ needs.set-env.outputs.release }}
          git push origin ${{ needs.set-env.outputs.release }}

      - name: Create release
        uses: "actions/github-script@v6"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            try {
              await github.rest.repos.createRelease({
                draft: ${{ needs.set-env.outputs.environment == 'staging' }},
                generate_release_notes: true,
                name: "${{ needs.set-env.outputs.release }}",
                owner: context.repo.owner,
                prerelease: ${{ needs.set-env.outputs.environment == 'staging' }},
                repo: context.repo.repo,
                tag_name: "${{ needs.set-env.outputs.release }}",
              });
            } catch (error) {
              core.setFailed(error.message);
            }

  deploy-image:
    name: Deploy to ${{ needs.set-env.outputs.environment }} (${{ needs.set-env.outputs.release }})
    needs: [ build-and-push-image, set-env ]
    runs-on: ubuntu-22.04
    environment: ${{ needs.set-env.outputs.environment }}
    steps:
      - name: Azure login with ACA credentials
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ACA_CREDENTIALS }}

      - name: Update Azure Container Apps Revision
        uses: azure/CLI@v1
        with:
          azcliversion: 2.40.0
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp update \
              --name ${{ secrets.ACA_CONTAINERAPP_NAME }} \
              --resource-group ${{ secrets.ACA_RESOURCE_GROUP }} \
              --image ${{ secrets.ACR_URL }}/${{ env.DOCKER_IMAGE }}:${{ needs.set-env.outputs.release }} \
              --output none

  cypress-tests:
      needs: [ deploy-image, set-env ]
      if: needs.set-env.outputs.environment == 'test' || needs.set-env.outputs.environment == 'development'
      environment: ${{ needs.set-env.outputs.environment }}
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: Dfe.Academies.External.Web/CypressTests
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup node.js
          uses: actions/setup-node@v3
          with:
            node-version: ${{ env.NODE_VERSION }}
        
        - name: Npm install
          run: npm install
        
        - name: Run cypress
          env:
            URL: ${{ secrets.URL }}
            LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
            LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
          run: npm run cy:run
        
        - name: upload report
          uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: screenshots
            path: Dfe.Academies.External.Web/CypressTests/cypress/screenshots
